---
parser: babel-eslint

parserOptions:
    ecmaVersion: 2018
    sourceType: module
    ecmaFeatures:
        impliedStrict: true
        jsx: true
    flowtype:
        onlyFilesWithFlowAnnotation: false

extends:
  - '@lectrum/eslint-config-core'

rules:
    indent: [ 2, 4, SwitchCase: 1 ]
    arrow-spacing: [2, { before: true, after: true }]
    key-spacing: [ 2, { beforeColon: false, afterColon: true, align: value } ]
    comma-dangle: [ 2, { arrays: always-multiline, objects: always-multiline, functions: always-multiline, imports: always-multiline, exports: always-multiline }]
    lines-around-comment: [2, {
        beforeBlockComment: true,
        afterBlockComment:  false,
        beforeLineComment:  true,
        afterLineComment:   false
    }]