openapi: 3.0.1
info:
  version: 0.0.1
  title: School API
  description: School API
servers:
  - url: 'http://localhost:3000'
  
paths:
  /teachers:
    get:
      summary: returns teachers collection
      responses:
        '200':
          description: displays teachers collection successfully
        '404':
          description: teachers collection was not found
        '500': 
          description: server not found
    post:
      summary: inserting changes and data
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: changes were implemented successfully 
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    put:
      summary: editing data
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: changes are saved
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: data was removed
      responses:
        '200':
          description: data was removed successfully
        '404':
          description: data not found
  /teachers/{teacherId}:
    get:
      summary: returns teachers Id
      parameters: 
        - name: teacherId
          in: path
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: teachers Id was successfully returned
        '404':
          description: teachers is not existed
        '500':
          description: servers not found
          content:
            application/json:
              schema:
                type: object
          
    post:
      summary: returns something
      parameters: 
        - name: teacherId
          in: path
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: returns ok    
          
    put:
      summary: returns something
      parameters: 
        - name: teacherId
          in: path
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: returns ok
          
    delete:
      summary: returns something
      parameters: 
        - name: teacherId
          in: path
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: returns ok
          
components:
  schemas:
     User:
      properties:
        id:
          type: integer
          example: 34
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic